### ISSUE TITLE
node 16 actions are being deprecated

### ISSUE THREAD

**Issue by sukoneck** [Mozilla-Actions/sccache-action#119]
warning from gihub actions:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: mozilla-actions/sccache-action@v0.0.3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by metachris** [comment]
Please update. Would be great not to see these errors on every build!

**Comment by Xuanwo** [comment]
We have already bumped to node 20. Just need a new release.

**Comment by sylvestre** [comment]
Just push a new release

**Comment by Sewer56** [comment]
`0.0.5` was released, and should fix it.
Hence the issue being closed.
