### ISSUE TITLE
Not caching my binary crate

### ISSUE THREAD

**Issue by xrl** [Mozilla-Actions/sccache-action#30]
I am trying to run the `cargo test` suite for binary crate, one with a `Cargo.lock` and fixed to `stable`. But the post-run log for sccache is showing not much happening. Here are two examples of my code base with the sccache action:

 * https://github.com/rdkit-rs/cheminee/actions/runs/4505948589 (using `RUSTFLAG: "-C incremental=false"` env var)
 * https://github.com/rdkit-rs/cheminee/actions/runs/4505982189/jobs/7932342070 (using `CARGO_INCREMENTAL=0` env var)

The post-run logs will show that things are caching:

```
Non-cacheable reasons:
incremental                         236
crate-type                           65
-                                     1
-E                                    1

Cache location                  ghac, name: sccache-v0.4.0, prefix: /sccache/
Version (client)                0.4.0
```

What's the preferred way of using `sccache` to speed up a `cargo test` invocation?

**Comment by sylvestre** [comment]
Not sure what you mean here

The first url contains the following:
```
Compile requests                    318
Compile requests executed           246
Cache hits                          245
Cache hits (C/C++)                   14
Cache hits (Rust)                   231
```
which seems legit to me.

Also, sccache doesn't cache the binaries but the various objects files.

**Comment by xrl** [comment]
OK, I guess I thought it'd be faster. Thanks for taking a look!
