### ISSUE TITLE
Errors running this action

### ISSUE THREAD

**Issue by yaleman** [Mozilla-Actions/sccache-action#41]
We started getting this today, any idea why it'd happen?

```text
Run mozilla-actions/sccache-action@v0.0.3
Error: HttpError: API rate limit exceeded for installation ID 16164673.
Error: API rate limit exceeded for installation ID 16164673.
```

Logs: https://github.com/yaleman/kanidm/actions/runs/4860505346/jobs/8664504311

**Comment by Xuanwo** [comment]
If you use `sccache-action` without specifying a version, it will call the GitHub API to fetch the latest version which could lead to API limit. To avoid this, please either specify the exact version or set a token for it.

https://github.com/Mozilla-Actions/sccache-action/blob/9a68c4d04b002581267169acd450e97504f82dd5/action.yml#L5-L10

**Comment by yaleman** [comment]
So just to check, would I use `0.4.2` or `v0.4.2` to specify the version?

**Comment by yaleman** [comment]
Never mind, figured it out 😄 

```yaml
 with:
    version: "v0.4.2"
```
