### ISSUE TITLE
Ability to set cache key (prefix/suffix)

### ISSUE THREAD

**Issue by jonashaag** [Mozilla-Actions/sccache-action#43]
If I'm caching builds for various matrix style configurations, I might want to keep separate caches by configuration.

Would be nice to be able to pass a cache key prefix/suffix to the action where I encode that configuration.

**Comment by Xuanwo** [comment]
> If I'm caching builds for various matrix style configurations, I might want to keep separate caches by configuration.

Hi, all cache are already hashed by inputs. There is no need to keep separate caches.

**Comment by jonashaag** [comment]
I don’t understand your response, can you please try to rephrase it?

**Comment by Xuanwo** [comment]
> I don’t understand your response, can you please try to rephrase it?

We don't need to separate caches

**Comment by jonashaag** [comment]
Example: I'm building a library for multiple CPU architectures. Objects for all architectures will end up in the same cache, right? I guess that's inefficient because then a CI run will  load and save a bunch of cache objects that can never be used.

**Comment by Xuanwo** [comment]
> Objects for all architectures will end up in the same cache, right?

No, multiple CPU architectures will lead to different cache entries. Please note that sccache's ghac support is different from actions/cache: https://xuanwo.io/en-us/reports/2023-04/

**Comment by Xuanwo** [comment]
It appears that this issue has already been resolved. Please do not hesitate to reopen it if you encounter any further problems.
