### ISSUE TITLE
Tag a new release for node20 bump?

### ISSUE THREAD

**Issue by fasterthanlime** [Mozilla-Actions/sccache-action#94]
I discovered https://github.com/Mozilla-Actions/sccache-action/issues/90 was already solved, but the latest tag (v0.0.3 doesn't include that change). Can someone tag v0.0.4 or something?

(I know I can pin to a commit, I'd just like the warning to be resolved for everyone by default.)

**Comment by sylvestre** [comment]
done, thanks for the ping
https://github.com/Mozilla-Actions/sccache-action/releases/tag/v0.0.4
